version = 0.1

[default]
[default.global.parameters]
stack_name = "experta-ai-social-manager"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Environment=\"dev\" BedrockClaudeModelId=\"global.anthropic.claude-opus-5\" BedrockClaudeFastModelId=\"global.anthropic.claude-sonnet-5\" BedrockImageModelId=\"stability.stable-image-ultra-v1:0\""
stack_name = "onzo"
s3_prefix = "onzo"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
